
springdoc:
  api-docs.path: /api-docs
  swagger-ui.path: /swagger-ui.html

spring:
  datasource: 
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_SERVER:localhost}:${DB_PORT:3306}/${DB_NAME:demo}?useUnicode=true&characterEncoding=utf-8
    username: ${DB_USERNAME:user00}
    password: ${DB_PASSWORD:admin1234}
    hikari:
      connection-timeout: 5000
      validation-timeout: 1000
      maximum-pool-size: 30
      minimum-idle: 2
          
  jpa:
    database-platform: org.hibernate.dialect
    hibernate:
      ddl-auto: none
      
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl    
    properties: 
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: true
        format_sql: true
        
        
        
